### ISSUE TITLE
Problem Export CA, if filter any device is selectionned with linux

### ISSUE THREAD

**Issue by Des3er** [nicolonsky/ConditionalAccessDocumentation#10]
Hello, I try to export 28 CA but the powershell extrat only 15 CA but another is tagged any device ( Linux included)

But If linux or any device selected, the ca is not extrated ?

Have you solution ?

Thank a lot

**Comment by nicolonsky** [comment]
Did you switch to the beta endpoint? `Select-MgProfile -Name "Beta"`. Usually policies with preview features are only visible on the beta version of the API.
