### ISSUE TITLE
Authentication prompts repeating

### ISSUE THREAD

**Issue by Fraser-AW** [nicolonsky/ConditionalAccessDocumentation#12]
Since the last update I'm getting constant pop-up auth requests, I've tried with a couple of different accounts in different tenants with the exact same thing.

**Comment by nicolonsky** [comment]
Did you pas `-ContextScope Process` to the `Connect-MgGraph` commandlet?

**Comment by nicolonsky** [comment]
`Connect-Graph -ContextScope Process`

**Comment by Fraser-AW** [comment]
Ah, worked a treat, thanks!
