### ISSUE TITLE
While exporting getting the error "Get-MgProfile : The term 'Get-MgProfile' is not recognized as the name of a cmdlet"

### ISSUE THREAD

**Issue by shbhard09** [nicolonsky/ConditionalAccessDocumentation#14]
As there is a separate module for Beta Commands then i guess we do not need to do select-mgprofile.
and while exporting the if the CAP has following setting configured : 
![image](https://github.com/nicolonsky/ConditionalAccessDocumentation/assets/146855323/c0f8b745-8051-4d1e-bde4-a9262d4619b6)

Then this is not included in the exported CSV.

**Comment by svhelden** [comment]
Forked a version that supports the new Beta modules: https://github.com/svhelden/ConditionalAccessDocumentationBeta/tree/master

**Comment by nicolonsky** [comment]
Adressed by c4557a563320da7af7777f7f173c0a05f9a64917
