### ISSUE TITLE
Execution command not always correct

### ISSUE THREAD

**Issue by svhelden** [nicolonsky/ConditionalAccessDocumentation#17]
This instruction has two issues:

`& "C:\Users\$env:USERNAME\Documents\WindowsPowerShell\Scripts\Invoke-ConditionalAccessDocumentation.ps1"`

- User profile is not always in "C:\Users\$env:USERNAME" but always in "$env:USERPROFILE"
- In Powershell 7, folder is "PowerShell" not "WindowsPowerShell"

**Comment by nicolonsky** [comment]
Adjusted instructions to call script directly - assuming the PowerShell profile is configured accordingly / in the default manner.
