### ISSUE TITLE
Get-MgIdentityConditionalAccessPolicy : Could not load file or assembly 'Microsoft.Graph.Authentication

### ISSUE THREAD

**Issue by vn82catu** [nicolonsky/ConditionalAccessDocumentation#2]
Get-MgIdentityConditionalAccessPolicy : Could not load file or assembly 'Microsoft.Graph.Authentication, Version=0.9.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the 
file specified.
At C:\ConditionalAccessDocumentation-master\Invoke-ConditionalAccessDocumentation.ps1:335 char:1
+ $conditionalAccessPolicies = Get-MgIdentityConditionalAccessPolicy -A ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgIdentityC...cessPolicy_List], FileNotFoundException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgIdentityConditionalAccessPolicy_List

**Comment by vn82catu** [comment]
Thank you for your code. Any idea what this might be ?

**Comment by t0feind** [comment]
Hi Nicola,

I experince the same problem. Are am I missing something?

**Comment by nicolonsky** [comment]
@vn82catu @t0feind this is related to module dependencies, ensure that you have the `Microsoft.Graph.Authentication` module installed and available under version 0.9.1. When I had a newer version present (besides 0.9.1) I encountered the same issue as you. 
Deleting any newer versions solved the problem:
![image](https://user-images.githubusercontent.com/32899754/102768948-40fc0600-4382-11eb-89da-46a7428911a9.png)

(Could only repro this one in PowerShell 5.1; on PowerShell 7 did not interferer)
