### ISSUE TITLE
Issue during Install-Script -Name Invoke-ConditionalAccessDocumentation -Scope CurrentUser

### ISSUE THREAD

**Issue by PhKinkel** [nicolonsky/ConditionalAccessDocumentation#4]
PackageManagement\Install-Package : The following commands are already available on this system:'Get-MgIdentityConditionalAccessNamedLocation,Get-MgIdentityConditionalAcce
ssPolicy,New-MgIdentityConditionalAccessNamedLocation,New-MgIdentityConditionalAccessPolicy,Remove-MgIdentityConditionalAccessNamedLocation,Remove-MgIdentityConditionalAcc
essPolicy,Update-MgIdentityConditionalAccessNamedLocation,Update-MgIdentityConditionalAccessPolicy'. This module 'Microsoft.Graph.Identity.ConditionalAccess' may override 
the existing commands. If you still want to install this module 'Microsoft.Graph.Identity.ConditionalAccess', use -AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:3538 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by nicolonsky** [comment]
`The following commands are already available on this system` - so you have a module conflict on your machine because you have other versions installed on your machine
