### ISSUE TITLE
Unable to get the full list of Policies in both BETA and V1.0 Endpoint

### ISSUE THREAD

**Issue by HEVARY** [nicolonsky/ConditionalAccessDocumentation#5]
On behalf of the customer (Accenture)

Unable to get the full list of CA policies using this script, it used to work before.
It is only showing 75, previously it used to display all 83.

**Comment by nicolonsky** [comment]
@HEVARY The script relies on the Microsoft Graph PowerShell SDK modules, I am using them regularly and not aware of any bug leading to missing policies. Does your tenant include policies targeting service principals (as these are only available on the beta endpoint)? What's the output of `Get-MgIdentityConditionalAccessPolicy`?
