### ISSUE TITLE
Device State Deprecated

### ISSUE THREAD

**Issue by tanktopSecurity** [nicolonsky/ConditionalAccessDocumentation#8]
Microsoft has deprecated the Device States: [https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-conditions#device-state-preview](url)

Would you kindly add the new Device Filter condition to the script? It's located here: $conditionalAccessPolicy.Conditions.AdditionalProperties.devices.deviceFilter

**Comment by nicolonsky** [comment]
@tanktopSecurity thanks for the heads-up. Updated this within the most recent release https://github.com/nicolonsky/ConditionalAccessDocumentation/releases/tag/v1.6.0
