### ISSUE TITLE
Get-ConditionalAccess null value

### ISSUE THREAD

**Issue by katpedraza** [nicolonsky/ConditionalAccessDocumentation#9]
When I run the Invoke-ConditionalAccessDocumentation I get the following error from the get-conditionalAccess PS. I do get all the data, but wondering if we can get the error fixed. 

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\IntuneDocumentation\Internal\Get-ConditionalAccess.ps1:18 char:9
+         $errorResponse = $ex.Response.GetResponseStream()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by nicolonsky** [comment]
@katpedraza you are using a different module than mine if you double check your path: `\Modules\IntuneDocumentation`. Probably the Cmdlet is being overridden by another

**Comment by katpedraza** [comment]
I am not. Module information is below. 

Script     2.0.19     IntuneDocumentation                 {Invoke-ConditionalAccessDocumentation, Invoke-IntuneDocum.

**Comment by nicolonsky** [comment]
@katpedraza ‘ IntuneDocumentation‘ is not the name of this script.
